name: clean_provider_architecture
description: "A new Flutter project."
version: 2025.0.1+2025.0.1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.1.2
  # Location Services
  geolocator: ^14.0.0
  location: ^8.0.0
  background_location: ^0.13.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.0
  geocoding: ^3.0.0
  # Maps
  google_maps_flutter: ^2.10.1
  google_maps_cluster_manager_2: ^3.2.0
  # Storage
  hive: ^2.2.3
  path_provider: ^2.1.3
  # Permissions
  permission_handler: ^11.0.0
  # Utils
  intl: ^0.19.0
  collection: ^1.18.0
  # UI
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  after_layout: ^1.2.0

dev_dependencies:
  build_runner: any
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: "assets/fonts/Inter_28pt-Thin.ttf"
          weight: 300
        - asset: "assets/fonts/Inter_28pt-Light.ttf"
          weight: 400
        - asset: "assets/fonts/Inter_28pt-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Inter_28pt-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Inter_28pt-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Inter_28pt-ExtraBold.ttf"
          weight: 800
    - family: SFPro
      fonts:
        - asset: "assets/fonts/SF-Pro-Display-Ultralight.otf"
          weight: 200
        - asset: "assets/fonts/SF-Pro-Display-Light.otf"
          weight: 300
        - asset: "assets/fonts/SF-Pro-Display-Regular.otf"
          weight: 400
        - asset: "assets/fonts/SF-Pro-Display-Medium.otf"
          weight: 500
        - asset: "assets/fonts/SF-Pro-Display-Semibold.otf"
          weight: 600
        - asset: "assets/fonts/SF-Pro-Display-Bold.otf"
          weight: 700
        - asset: "assets/fonts/SF-Pro-Display-Heavy.otf"
          weight: 800

  assets:
    - assets/
    - assets/fonts/
